### ISSUE TITLE
pasmp : over 1 year old

### ISSUE THREAD

**Issue by jBitHub** [BeRo1985/pasmp#14]
Hello,
I find your projects very interesting. Is there a reason why you do not update the submodule "pasmp". Since over a year I can see changes in Fork. But I cannot update them with "git pull".
![grafik](https://user-images.githubusercontent.com/39560844/97707474-a258d480-1ab7-11eb-8b98-6101d785bad3.png)

I already thought that Fork is buggy. Therefore I have already contacted the Fork team.
https://github.com/fork-dev/TrackerWin/issues/996

**Comment by BeRo1985** [comment]
Hm, unfortunately I cannot reproduce that. Because `git status` and `git log` say something else, so that the error is not in this repo. See screenshots. 

![image](https://user-images.githubusercontent.com/428863/97709702-0d57da80-1abb-11eb-987e-7cb1db67afe3.png)

![image](https://user-images.githubusercontent.com/428863/97709906-5871ed80-1abb-11eb-9f14-d5b1d00901f9.png)

**Comment by DanPristupov** [comment]
@BeRo1985 thank you for the answer. What is the state of the parent repository?

Could you run `git submodule status externals/pasmp` and `git status` in the `pasvulkan` repo and show the output please?


Here's what I see right after cloning `pasvulkan`:

```
dan pasvulkan % git submodule status externals/pasmp
 70e4a2c5aa4859296a460dd3a1596e535e3022b8 externals/pasmp (70e4a2c)

dan pasvulkan % git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

As you can see the `master` branch in the `pasvulkan` repo points to the `70e4a2c` commit in the `pasmp` submodule. OP asks, why `pasvulkan` doesn't use the latest changes from `pasmp`.

**Comment by BeRo1985** [comment]
So I'm wondering, what does a git client (Fork) have to do with Vulkan or my PasVulkan project? I would recommend a direct external dependency to this PasMP git repo instead a indirect one over my PasVulkan project in this case. But of course, I'll update the PasMP external dep. in my PasVulkan project.

**Comment by DanPristupov** [comment]
Fork should probably not be mentioned there to not confuse you :).

Initially OP supposed that Fork has a bug because submodules in the PasVulkan  suddenly stopped being updated in August 2019. I explained that Fork is not related and recommended to ask you directly about the reason why PasVulkan still points to the 1 year old commit of the PasMP repo.

**Comment by jBitHub** [comment]
I am not a git expert and therefore I use a client. Fork is the best I have found. I don't usually work via the console. The console is also very confusing. The client fork has a good graphical overview.
The submodules have now been updated. 👍 

I thank you both very much for your efforts.
