### ISSUE TITLE
Potential issues regarding TPasMPThreadSafeQueue.Enqueue (Michael-Scott-Algorithm)

### ISSUE THREAD

**Issue by wbochtler** [BeRo1985/pasmp#15]
Hello Benjamin,
I'm just trying to understand and learn from your implementation of the Michael-Scott queue algorithm.
Despite the risk of being completely wrong, I would like to point out the following possible issues regarding TPasMPThreadSafeQueue.Enqueue():

1. Lines 7930, 7931:
` Node^.Previous.PointerValue:=nil;
 Node^.Previous.TagValue:=0;`
 The initialization of  'Previous' is not clear to me as it is not used in the algorithm at all. According to the original publication I would expect the initalization of Node^.Next.PointerValue and Node^.Next.TagValue. BTW: In the constructor 'Previous' is also initialized.
2. Line 7948):
`OldNext.Value:=TPasMPInterlocked.CompareExchange(PPasMPThreadSafeQueueNode(fTail^.PointerValue)^.Next.Value,Temporary.Value,Next.Value);`
According to the original publication I would expect Tail^.PointerValue instead of fTail^.PointerValue.

Kind regards,
Werner

**Comment by BeRo1985** [comment]
Good catch. However, the Michael Scott algorithm is generally use-after-free flawed (see https://web.archive.org/web/20160616232708/http://blog.shealevy.com/2015/04/23/use-after-free-bug-in-maged-m-michael-and-michael-l-scotts-non-blocking-concurrent-queue-algorithm/ ), which makes it practically useless without, for example, hazard pointers or other similar deferred-free-memory solutions. This is also the reason why it is ifdef-ed out here and the optimistic FIFO queuing algorithm ( http://people.csail.mit.edu/edya/publications/OptimisticFIFOQueue-journal.pdf ) is used here instead. And at least for the 1. point, it is rather merely because of code unification.
