### ISSUE TITLE
 how to release hashtable object ?

### ISSUE THREAD

**Issue by leeonsoft** [BeRo1985/pasmp#5]
Obj := TTestObject.Create;
  Obj.Name := 'James';
  ObjectHashTable := TPasMPHashTable<string, TObject>.Create();
  try
    ObjectHashTable.SetKeyValue('James', Obj);
    if ObjectHashTable.GetKeyValue('James', objout) then
    begin
      Writeln('Found Object...');
    end
    else
      Writeln('not Found Object...');
  finally
    ObjectHashTable.Free;
  end;
  Writeln(Obj.Name);

how to Iterative  HashTable Object ？

**Comment by BeRo1985** [comment]
To do this, you have to add a list of these objects yourself, because otherwise it would break the thread-safe principle of this PasMP hash-table construct, or at least it would make the implementation of it more complex, and thus possibly also slower, because more sync zones would be needed then, for to be able to provide such functionality in a thread-safe hash-table at all.  Because one thing you don't want, locks or more locks.

**Comment by leeonsoft** [comment]
Okay, I understand. Thank you
